services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    networks:
      - backbone
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    hostname: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: local
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - backbone

volumes:
  postgres:

networks:
  backbone:
    driver: bridge
